name: Publish on Release

on:
  release:
    types: created

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: trevor-scheer/federation/stargate
          username: ${{ github.actor }}
          password: ${{ secrets.TREVOR_PAT_FOR_GHCR }}
          workdir: /github/workspace/stargate
          registry: ghcr.io